id = "yocraft/qr-code"
name = "QR Code encoder"
version = "1.0.0"
plugin_api = 21
author = "yocraft"
license = "MIT"
deprecated = false
icon = "qrcode"
description = "Transform any text or url in a qr code"
tags = []
dependencies = []

[[widget]]
id = "widget"
entry = "widget.luau"

[[panel]]
id = "panel"
entry = "panel.luau"
width = 600
height = 600
placement = "floating"
position = "center"

[[setting]]
key = "generate_button"
type = "bool"
label_key = "settings.generate_button.label"
description_key = "settings.generate_button.description"
default = true

[[setting]]
key = "close_on_copy"
type = "bool"
label_key = "settings.close_on_copy.label"
description_key = "settings.close_on_copy.description"
default = false
