id = "notfinaldev/web-search"
name = "Web Search"
version = "1.4.0"
plugin_api = 18
author = "notfinaldev"
license = "MIT"
icon = "world"
description = "Open favourite websites or search the web from the Noctalia launcher."
tags = ["launcher", "network", "utility"]
dependencies = ["xdg-open"]

[[launcher_provider]]
id = "search"
entry = "launcher.luau"
prefix = "web"
glyph = "world-search"
include_in_global_search = true


[[setting]]
key = "provider"
type = "select"
label_key = "settings.provider.label"
description_key = "settings.provider.description"
default = "google"
options = [
    { value = "google", label_key = "settings.provider.options.google" },
    { value = "duckduckgo", label_key = "settings.provider.options.duckduckgo" },
    { value = "ecosia", label_key = "settings.provider.options.ecosia" },
    { value = "bing", label_key = "settings.provider.options.bing" },
    { value = "brave", label_key = "settings.provider.options.brave" },
    { value = "mojeek", label_key = "settings.provider.options.mojeek" },
]

[[setting]]
key = "links"
type = "string_list"
label_key = "settings.links.label"
description_key = "settings.links.description"
default = [
    "GitHub|https://github.com",
    "GitLab|https://gitlab.com",
    "Codeberg|https://codeberg.org",
    "Reddit|https://reddit.com",
    "YouTube|https://youtube.com",
    "Gmail|https://mail.google.com",
]
