id = "m4sc/profile-switcher"
name = "Profile Switcher"
version = "1.0.0"
plugin_api = 30

author = "m4sc"
license = "MIT"

description = "Switch and edit Noctalia appearance profiles."
icon = "palette"
tags = ["theming", "wallpaper", "utility"]
dependencies = []

[[service]]
id = "service"
entry = "service.luau"

[[widget]]
id = "profile"
entry = "widget.luau"

[[shortcut]]
id = "profiles"
entry = "shortcut.luau"

[[panel]]
id = "panel"
entry = "panel.luau"

width = 460
height = 460

placement = "floating"
position = "center"

keyboard_focus = "on_demand"
dismiss_on_outside_click = true


[[panel]]
id = "editor"
entry = "editor.luau"

width = 600
height = 720

placement = "floating"
position = "center"

keyboard_focus = "on_demand"
dismiss_on_outside_click = false
