id = "devpotatoes/whosthatpokemon"
name = "Whos That Pokémon"
version = "1.0.0"
plugin_api = 3
author = "dev.potatoes"
license = "GPL-3.0"
deprecated = false
icon = "device-gamepad"
description = "A simple and fully offline Pokémon mini-game."
tags = ["fun", "panel"]
dependencies = []

[[launcher_provider]]
id = "launcher"
prefix = "wtp"
glyph = "device-gamepad"
entry = "launcher.luau"

[[panel]]
id = "panel"
entry = "panel.luau"
width = 256
height = 256