name: Notify Plugin Authors for Issues

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  notify-plugin-authors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: 3.14

      - name: Install dependencies
        run: pip install PyGithub

      - name: Notify Authors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python3 .github/workflows/issues-notify-plugin-authors.py
